SELECT --S.EM_ITEM_NUM, 
        CASE WHEN COST.AMT IS NULL THEN 'N' ELSE 'Y' END AS OS_FLAG,
        I.GNRC_ID,
        I.GNRC_NAM,
        I.EQV_ID AS GLOBAL_ID,
        I.GNRC_NAM || ' ' || EI.GNRC_DRG_STRNTH_DSCR || ' ' || I.PKG_DSCR || ' ' || I.TOTAL_PKG_SIZE AS GLOBAL_ID_DSCR,
        I.TOTAL_PKG_SIZE,
        S.SPLR_ACCT_ID,
        S.SPLR_ACCT_NAM,
        SPLR.LEAD_SPLR_NAM,
        SUM(S.SLS_CR_AMT) SLS_AMT,
        SUM(S.SLS_CR_QTY) SLS_QTY
FROM "PRD_PSAS_DB"."RPT"."T_NET_CUST_SALES" S
    LEFT JOIN "PRD_PSAS_DB"."RPT"."GX_EQV_ID_ITEMS_EXPANDED" I ON S.EM_ITEM_NUM = I.EM_ITEM_NUM
    LEFT JOIN "PRD_PSAS_DB"."RPT"."T_IW_EM_ITEM" EI ON S.EM_ITEM_NUM = EI.EM_ITEM_NUM
    LEFT JOIN "PRD_PSAS_DB"."RPT"."PHARMA_SPLR_HIERARCHY" SPLR ON S.SPLR_ACCT_ID = SPLR.SPLR_ACCT_ID
    LEFT JOIN "PRD_DATA_LAKE_DB"."PSAS_HANA"."T_ITEM_COST" COST 
            ON S.EM_ITEM_NUM = COST.EM_ITEM_NUM AND EFF_DT <= CURRENT_DATE AND CURRENT_DATE <= END_DT AND COST_ID = 1855
WHERE DATEDIFF('month', PROC_WRK_DT, CURRENT_DATE) <= 3 
    AND S.GNRC_FLG = 'Y'
GROUP BY --S.EM_ITEM_NUM, 
         OS_FLAG,
         I.GNRC_ID,
         I.GNRC_NAM,
         I.EQV_ID,
         I.GNRC_NAM || ' ' || EI.GNRC_DRG_STRNTH_DSCR || ' ' || I.PKG_DSCR || ' ' || I.TOTAL_PKG_SIZE,
         I.TOTAL_PKG_SIZE,
         S.SPLR_ACCT_ID,
         S.SPLR_ACCT_NAM,
         SPLR.LEAD_SPLR_NAM;
         
--------------------------------------------------------------------------------
------------------------------------v2------------------------------------------
--------------------------------------------------------------------------------
--RAD,WMT EXC: line 57, 86, 102, 149
CREATE OR REPLACE TEMPORARY TABLE NS_FLAGS AS --SELECT TOP 10 * FROM NS_FLAGS WHERE GNRC_ID = '14853'
(SELECT DISTINCT EI.GNRC_ID, MAX(CASE WHEN SPLR.LEAD_SPLR_NAM LIKE '%NORTHSTAR%' THEN 'Y' ELSE 'N' END) AS NS_FLG
    FROM "PRD_PSAS_DB"."RPT"."T_IW_EM_ITEM" EI 
        LEFT JOIN "PRD_PSAS_DB"."RPT"."PHARMA_SPLR_HIERARCHY" SPLR ON EI.SPLR_ACCT_ID = SPLR.SPLR_ACCT_ID
   WHERE EI.GNRC_IND = 'Y' AND EI.GNRC_ID <> '' AND ITEM_ACTVY_CD = 'A'
   GROUP BY 1);
   
CREATE OR REPLACE TEMPORARY TABLE OS_FLAGS
AS (SELECT DISTINCT EI.GNRC_ID, MAX(CASE WHEN COST.AMT IS NULL THEN 'N' ELSE 'Y' END) AS OS_FLG
    FROM "PRD_PSAS_DB"."RPT"."T_IW_EM_ITEM" EI
        LEFT JOIN "PRD_ENT_PL_DATALAKE_DB"."GX_RPT"."V_T_ITEM_COST" COST 
            ON EI.EM_ITEM_NUM = COST.EM_ITEM_NUM AND EFF_DT <= CURRENT_DATE AND CURRENT_DATE <= END_DT AND COST_ID = 1855
    WHERE EI.GNRC_IND = 'Y' --AND EI.GNRC_ID = '48191'
    GROUP BY 1);

CREATE OR REPLACE TEMPORARY TABLE GCN_SALES
AS (SELECT GNRC_ID,
        COUNT(DISTINCT I.TOTAL_PKG_SIZE) PKG_SIZE_COUNT, SUM(SLS_CR_AMT) SLS_AMT 
    FROM "PRD_PSAS_DB"."RPT"."T_NET_CUST_SALES" S 
        LEFT JOIN "PRD_PSAS_DB"."RPT"."GX_EQV_ID_ITEMS_EXPANDED" I ON S.EM_ITEM_NUM = I.EM_ITEM_NUM
        LEFT JOIN "PRD_PSAS_DB"."RPT"."PHARMA_SPLR_HIERARCHY" SPLR ON S.SPLR_ACCT_ID = SPLR.SPLR_ACCT_ID
    WHERE DATEDIFF('month', PROC_WRK_DT, CURRENT_DATE) <= 3 --AND S.NATL_GRP_NAM NOT IN ('RITE AID','WALMART INC')
          AND S.GNRC_FLG = 'Y' --AND GNRC_ID = '27452' 
    GROUP BY 1);

CREATE OR REPLACE TEMPORARY TABLE NS_PKG_SIZE AS
(SELECT EI.GNRC_ID, 
    LISTAGG(DISTINCT CASE WHEN SPLR.LEAD_SPLR_NAM LIKE '%NORTHSTAR%' THEN CAST(I.TOTAL_PKG_SIZE AS NUMERIC) ELSE NULL END, ' ') AS NS_PKG_SIZES
    FROM "PRD_PSAS_DB"."RPT"."T_IW_EM_ITEM" EI 
        LEFT JOIN "PRD_PSAS_DB"."RPT"."GX_EQV_ID_ITEMS_EXPANDED" I ON EI.EM_ITEM_NUM = I.EM_ITEM_NUM
        LEFT JOIN "PRD_PSAS_DB"."RPT"."PHARMA_SPLR_HIERARCHY" SPLR ON EI.SPLR_ACCT_ID = SPLR.SPLR_ACCT_ID
    WHERE EI.GNRC_IND = 'Y' --AND EI.GNRC_ID = '27452'
    GROUP BY 1);
    
CREATE OR REPLACE TEMPORARY TABLE GID_SALES --SELECT TOP 10 * FROM GID_SALES WHERE EQV_ID = '8871'
AS (SELECT I.EQV_ID, 
        CASE WHEN SPLR.LEAD_SPLR_NAM LIKE '%NORTHSTAR%' THEN 'Y' ELSE 'N' END AS NS_FLG,
        CASE WHEN COST.AMT IS NOT NULL THEN 'Y' ELSE 'N' END AS OS_FLG,
        I.TOTAL_PKG_SIZE,
        SUM(S.SLS_CR_AMT) SLS_AMT,
        SUM(S.SLS_CR_QTY) SLS_QTY,
        SUM(S.SLS_CR_QTY) * AVG(I.TOTAL_PKG_SIZE) AS PILLS,
        DIV0(SLS_AMT,PILLS) AS AVG_PRICE_PER_PILL
    
    FROM "PRD_PSAS_DB"."RPT"."T_NET_CUST_SALES" S   
            LEFT JOIN "PRD_PSAS_DB"."RPT"."GX_EQV_ID_ITEMS_EXPANDED" I ON S.EM_ITEM_NUM = I.EM_ITEM_NUM
            LEFT JOIN "PRD_PSAS_DB"."RPT"."PHARMA_SPLR_HIERARCHY" SPLR ON S.SPLR_ACCT_ID = SPLR.SPLR_ACCT_ID
            LEFT JOIN "PRD_ENT_PL_DATALAKE_DB"."GX_RPT"."V_T_ITEM_COST"  COST 
                ON S.EM_ITEM_NUM = COST.EM_ITEM_NUM AND EFF_DT <= CURRENT_DATE AND CURRENT_DATE <= END_DT AND COST_ID = 34 

    WHERE DATEDIFF('month', PROC_WRK_DT, CURRENT_DATE) <= 3 --AND S.NATL_GRP_NAM NOT IN ('RITE AID','WALMART INC')
          AND S.GNRC_FLG = 'Y' --and GNRC_ID = '27452'-- AND EQV_ID = '1486'
    GROUP BY 1,2,3,4);
    
CREATE OR REPLACE TEMPORARY TABLE GID_AVG_LC AS
(SELECT I.EQV_ID, MIN(LC.TOTAL_COST) AS LANDED_COST
    FROM (SELECT DISTINCT EQV_ID, EM_ITEM_NUM FROM "PRD_PSAS_DB"."RPT"."GX_EQV_ID_ITEMS_EXPANDED") I
    LEFT JOIN "PRD_DATA_LAKE_DB"."PSAS_HANA"." T_NSTAR_COST" LC ON I.EM_ITEM_NUM = LC.EM_ITEM_NUM          
    WHERE LC.PRC_CURR_CD = 'C'
    GROUP BY 1);

CREATE OR REPLACE TEMPORARY TABLE SEG_SALES AS
(SELECT I.EQV_ID, CHN.PRIMARY_SEGMENT SEGMENT, SUM(S.SLS_CR_AMT) SLS_AMT
    FROM "PRD_PSAS_DB"."RPT"."T_NET_CUST_SALES" S 
        LEFT JOIN "PRD_PSAS_DB"."RPT"."GX_EQV_ID_ITEMS_EXPANDED" I ON S.EM_ITEM_NUM = I.EM_ITEM_NUM
        LEFT JOIN sbx_psas_db.sbx_ea_all.t_md_fpa_chn CHN ON try_to_number(S.cust_chn_id) = (CHN.CHAIN_ID) --SELECT TOP 10 * FROM sbx_psas_db.sbx_ea_all.t_md_fpa_chn
    WHERE DATEDIFF('month', PROC_WRK_DT, CURRENT_DATE) <= 3 --AND S.NATL_GRP_NAM NOT IN ('RITE AID','WALMART INC')
          AND S.GNRC_FLG = 'Y' AND S.SLS_CR_AMT <> 0 --AND EQV_ID = '2239'
    GROUP BY 1,2);
    
    
--main
SELECT ZZ.*,   
        SUM(CASE WHEN SG.SEGMENT = 'RNA' THEN SG.SLS_AMT ELSE 0 END) * 4 AS GID_RNA_SALES,
        SUM(CASE WHEN SG.SEGMENT = 'ISMC' THEN SG.SLS_AMT ELSE 0 END) * 4 AS GID_ISMC_SALES,
        SUM(CASE WHEN SG.SEGMENT = 'MHS' THEN SG.SLS_AMT ELSE 0 END) * 4 AS GID_MHS_SALES,
        SUM(CASE WHEN SG.SEGMENT NOT IN ('RNA','ISMC','MHS') OR SG.SEGMENT IS NULL THEN SG.SLS_AMT ELSE 0 END) * 4 AS GID_OTHER_SEG_SALES,
        
        DIV0(SUM(CASE WHEN SG.SEGMENT = 'RNA' THEN SG.SLS_AMT ELSE 0 END) , SUM(SG.SLS_AMT)) AS PERC_GID_RNA_SALES,
        DIV0(SUM(CASE WHEN SG.SEGMENT = 'ISMC' THEN SG.SLS_AMT ELSE 0 END) , SUM(SG.SLS_AMT)) AS PERC_GID_ISMC_SALES,
        DIV0(SUM(CASE WHEN SG.SEGMENT = 'MHS' THEN SG.SLS_AMT ELSE 0 END) , SUM(SG.SLS_AMT)) AS PERC_GID_MHS_SALES,
        DIV0(SUM(CASE WHEN SG.SEGMENT NOT IN ('RNA','ISMC','MHS') OR SG.SEGMENT IS NULL THEN SG.SLS_AMT ELSE 0 END) , SUM(SG.SLS_AMT)) AS PERC_GID_OTHER_SEG_SALES

    FROM (SELECT Z.*,
            IFNULL(NS.NS_FLG,'N') AS NSTR_GCN,
            IFNULL(OS.OS_FLG,'N') AS OS_GCN,

            SUM(CASE WHEN Y.NS_FLG = 'Y' THEN Y.SLS_AMT ELSE 0 END) * 4 AS GID_NS_SALES,
            SUM(CASE WHEN Y.NS_FLG = 'Y' THEN Y.AVG_PRICE_PER_PILL ELSE 0 END) AS GID_NS_AVG_UNIT_PRICE,
            SUM(CASE WHEN Y.NS_FLG = 'N' AND Y.OS_FLG = 'Y' THEN Y.SLS_AMT ELSE 0 END) * 4 AS GID_OS_SALES,
            SUM(CASE WHEN Y.NS_FLG = 'N' AND Y.OS_FLG = 'Y' THEN Y.AVG_PRICE_PER_PILL ELSE 0 END) AS GID_OS_AVG_UNIT_PRICE,
            SUM(CASE WHEN Y.NS_FLG = 'N' AND Y.OS_FLG = 'N' THEN Y.SLS_AMT ELSE 0 END) * 4 AS GID_OTHER_PGM_SALES,
            SUM(CASE WHEN Y.NS_FLG = 'N' AND Y.OS_FLG = 'N' THEN Y.AVG_PRICE_PER_PILL ELSE 0 END) AS GID_OTHER_AVG_UNIT_PRICE


    FROM (SELECT LPAD(I.GNRC_ID,5,'0') AS GNRC_ID,  
                MAX(I.GNRC_NAM) GNRC_NAM,
                I.EQV_ID AS GLOBAL_ID,
                CAST(I.TOTAL_PKG_SIZE AS NUMERIC) AS PKG_SIZE,
                X.PKG_SIZE_COUNT,
                PACK.NS_PKG_SIZES,
                X.SLS_AMT * 4 AS GCN_SALES,
                DIV0(LC.LANDED_COST, I.TOTAL_PKG_SIZE) GID_UNIT_LANDED_COST,
                SUM(S.SLS_CR_AMT) * 4 AS GID_SALES

        FROM "PRD_PSAS_DB"."RPT"."T_NET_CUST_SALES" S --SELECT top 10 * FROM "PRD_PSAS_DB"."RPT"."T_NET_CUST_SALES"
            LEFT JOIN "PRD_PSAS_DB"."RPT"."GX_EQV_ID_ITEMS_EXPANDED" I ON S.EM_ITEM_NUM = I.EM_ITEM_NUM
            LEFT JOIN GCN_SALES X ON I.GNRC_ID = X.GNRC_ID
            LEFT JOIN GID_AVG_LC LC ON I.EQV_ID = LC.EQV_ID
            LEFT JOIN NS_PKG_SIZE PACK ON I.GNRC_ID = PACK.GNRC_ID

        WHERE DATEDIFF('month', S.PROC_WRK_DT, CURRENT_DATE) <= 3 
            AND S.GNRC_FLG = 'Y' AND I.GNRC_ID <> '' AND S.SLS_CR_AMT <> 0 --AND I.EQV_ID = '14631'
            --AND S.NATL_GRP_NAM NOT IN ('RITE AID','WALMART INC')
          
        GROUP BY 1,3,4,5,6,7,8) Z 
          
        LEFT JOIN GID_SALES Y ON Z.GLOBAL_ID = Y.EQV_ID

        LEFT JOIN NS_FLAGS NS ON Z.GNRC_ID = NS.GNRC_ID
        LEFT JOIN OS_FLAGS OS ON Z.GNRC_ID = OS.GNRC_ID

        WHERE GCN_SALES IS NOT NULL 
        GROUP BY 1,2,3,4,5,6,7,8,9,10,11
        ) ZZ LEFT JOIN SEG_SALES SG ON ZZ.GLOBAL_ID = SG.EQV_ID
        
        WHERE PKG_SIZE_COUNT > 1 AND NSTR_GCN = 'Y' --AND GID_OS_SALES + GID_OTHER_PGM_SALES > 1000000 
                --AND GID_NS_SALES = 0 --AND GID_NS_SALES/GID_SALES < 0.30 --AND MAX_NS_PKG_SIZE <> 0  --AND (PKG_SIZE) <> (MAX_NS_PKG_SIZE) 

        GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
        ORDER BY 7 DESC,9 DESC
    ;
        
-- VALIDATE
select GNRC_ID, EQV_ID, CASE WHEN SPLR.LEAD_SPLR_NAM LIKE 'NORTHSTAR%' THEN 'NSTR' ELSE 'NON-NSTR' END AS SPLR, SUM(SLS_CR_AMT) 
FROM "PRD_PSAS_DB"."RPT"."T_NET_CUST_SALES" S   
            LEFT JOIN "PRD_PSAS_DB"."RPT"."GX_EQV_ID_ITEMS_EXPANDED" I ON S.EM_ITEM_NUM = I.EM_ITEM_NUM
            LEFT JOIN "PRD_PSAS_DB"."RPT"."PHARMA_SPLR_HIERARCHY" SPLR ON S.SPLR_ACCT_ID = SPLR.SPLR_ACCT_ID
where EQV_ID = '3318' and DATEDIFF('month', PROC_WRK_DT, CURRENT_DATE) <= 3 
    --and splr.lead_splr_nam like '%NORTHSTAR%' 
    and SLS_CR_AMT <> 0
group by 1,2,3;

SELECT DISTINCT EQV_ID, EM_ITEM_NUM, SELL_DSCR, SPLR_ACCT_NAM 
FROM "PRD_PSAS_DB"."RPT"."GX_EQV_ID_ITEMS_EXPANDED" I 
WHERE GNRC_IND = 'Y' AND EQV_ID = '3350'; 

SELECT * --DISTINCT EQV_ID, EM_ITEM_NUM
FROM "PRD_PSAS_DB"."RPT"."GX_EQV_ID_ITEMS_EXPANDED"
WHERE EM_ITEM_NUM IN (1571892,1571900,1566876,1566884,1566892,1566900,1566850,1566868,3908878,2327310,3952165,3952173,1531235,1531284,2309300,2309318,2329753,2327278,2327286,2327294,2309383,2309425,2309441,2313716,2313732,2313740,2313757,2301968,2311066,2311074,2311058,2321057,2321065,2321073,2321099,2321107,2301976,2308906,2308922,2309532,2309540,2309557,1598663,1598671,1571488,1571561,1571546,2308005
) and EQV_ID is null ;

select * from "PRD_PSAS_DB"."RPT"."T_IW_EM_ITEM"
WHERE EM_ITEM_NUM IN (1571892,1571900,1566876,1566884,1566892,1566900,1566850,1566868,3908878,2327310,3952165,3952173,1531235,1531284,2309300,2309318,2329753,2327278,2327286,2327294,2309383,2309425,2309441,2313716,2313732,2313740,2313757,2301968,2311066,2311074,2311058,2321057,2321065,2321073,2321099,2321107,2301976,2308906,2308922,2309532,2309540,2309557,1598663,1598671,1571488,1571561,1571546,2308005
) ;