--CREATE TABLE OF NORTHSTAR ITEMS
IF OBJECT_ID('tempdb..#NS_ITEMS') IS NOT NULL DROP TABLE #NS_ITEMS;

SELECT		E.EM_ITEM_NUM
			,EI.EQV_ID
			,E.SELL_DSCR
			,E.TOTAL_PKG_SIZE
			,E.GNRC_ID GCN
			,E.GNRC_NAM
			,CASE WHEN V_PRC_INJECT.EM_ITEM_NUM IS NOT NULL THEN 'Y' ELSE 'N' END INJECTABLE

INTO		#NS_ITEMS
FROM		REFERENCE.DBO.T_IW_EM_ITEM E
		
LEFT JOIN	GEPRS_PRODUCT.EQV.V_EQV_ID_ITEMS EI
ON			E.EM_ITEM_NUM = EI.EM_ITEM_NUM

LEFT JOIN	PHOENIX.RBP.V_PRC_INJECT
ON			V_PRC_INJECT.EM_ITEM_NUM = E.EM_ITEM_NUM

WHERE		E.SPLR_ACCT_NAM LIKE '%NORTHSTAR%' 
			AND E.ITEM_ACTVY_CD = 'A'
			AND E.E10_COST <> 0
			--AND E.EM_ITEM_NUM NOT IN ('3644796','3758760','3758778','3758786','3773926');

--SELECT EQV_ID, COUNT(EM_ITEM_NUM) AS COUNT FROM #NS_ITEMS GROUP BY EQV_ID ORDER BY 2 DESC
--SELECT distinct em_item_num FROM #NS_ITEMS


--CREATE TABLE OF EQV ITEMS
IF OBJECT_ID('tempdb..#ITEMS') IS NOT NULL DROP TABLE #ITEMS;

SELECT		E.EM_ITEM_NUM

INTO		#ITEMS
FROM		GEPRS_PRODUCT.EQV.V_EQV_ID_ITEMS E

JOIN		#NS_ITEMS N 
ON			E.EQV_ID = N.EQV_ID;

--SELECT * FROM #NS_ITEMS


--CREATE TABLE OF CURRENT CUSTOMERS BY CHAIN/SEGMENT
IF OBJECT_ID('tempdb..#CURR_CUSTS') IS NOT NULL DROP TABLE #CURR_CUSTS;

SELECT		DISTINCT V_CHN_SEGMENT_BY_CUST_TOT_SLS.CHN_ID
			,UPPER(V_CHN_SEGMENT_BY_CUST_TOT_SLS.CUSTOMER_NAME) AS CUSTOMER_NAME
			,CASE	WHEN V_CHN_SEGMENT_BY_CUST_TOT_SLS.FPA_SEGMENT LIKE 'RNA%' AND T_RNA_CHAINS.CHN_ID IS NULL THEN 'ISMC'
					ELSE V_CHN_SEGMENT_BY_CUST_TOT_SLS.FPA_SEGMENT END AS SEGMENT

INTO		#CURR_CUSTS
FROM		GX_RPT.dbo.V_CHN_SEGMENT_BY_CUST_TOT_SLS

LEFT JOIN	GX_RPT.dbo.T_RNA_CHAINS
ON			V_CHN_SEGMENT_BY_CUST_TOT_SLS.CHN_ID = T_RNA_CHAINS.CHN_ID

WHERE		V_CHN_SEGMENT_BY_CUST_TOT_SLS.FPA_SEGMENT IS NOT NULL
--AND			V_CHN_SEGMENT_BY_CUST_TOT_SLS.CUSTOMER_NAME NOT IN ('CVS HEALTH','WALGREENS','SUPERVALU','GIANT EAGLE','AHOLD');

--SELECT distinct customer_name FROM #CURR_CUSTS where customer_name in ('APCI','IPC','EPIC','CARE');


--PROGRAMS
IF OBJECT_ID('tempdb..#PGM_TYPES') IS NOT NULL DROP TABLE #PGM_TYPES;

SELECT		PGM_TYP_CD
			,CASE WHEN SCND_PGM_TYP_GRP_CD = '001' THEN 'ONESTOP' ELSE PGM_TYP_DSCR END PROGRAM

INTO		#PGM_TYPES
FROM		BTSMART.cbk.T_CCPRS_PGM_TYP

WHERE		PGM_TYP_CD <> '000';

--SELECT * FROM #PGM_TYPES;


--PULL SALES HISTORY WITHIN RNA
IF OBJECT_ID('tempdb..#SLS') IS NOT NULL DROP TABLE #SLS;
		
SELECT		LEFT(CONVERT(varchar, P.SLS_PROC_WRK_DT,112),6) YR_MONTH --select distinct yr_month from #sls
			,P.SLS_CUST_CHN_ID
			,#CURR_CUSTS.CUSTOMER_NAME
			,#CURR_CUSTS.SEGMENT
			,I.GNRC_NAM
			,I.GNRC_ID GCN
			,P.EM_ITEM_NUM
			,I.SELL_DSCR
			,EI.EQV_ID
			,I.SPLR_ACCT_NAM
			,CASE WHEN I.SPLR_ACCT_NAM LIKE '%NORTHSTAR%' THEN 'Y' ELSE 'N' END NSTR_FLG
			,CASE WHEN #PGM_TYPES.PROGRAM IS NULL AND P.CNTRC_LEAD_TP_ID IS NOT NULL THEN '3RD PARTY CONTRACT' ELSE #PGM_TYPES.PROGRAM END PROGRAM
			,CASE	WHEN P.ITEM_SUB_CD = 'Y' THEN 'OVERRIDE' 
				WHEN P.SUB_FLG = 'Y' THEN 'SUB'
				ELSE 'FILLED' END ORDR_TYPE
			,CASE	WHEN P.ITEM_SUB_CD IN ('O','A') THEN 'OMIT'
				WHEN P.ITEM_SUB_CD IN ('B','P') THEN 'ALWAYS'
				ELSE ' '
				END SUB_TYPE
			,P.YYITM_ECON_ORIG_ITEM_NUM ORIG_ORDR_ITEM
			,CASE WHEN #NS_ITEMS.EM_ITEM_NUM IS NOT NULL THEN 'Y' ELSE 'N' END NS_ORIG_ORDR
			--,CASE WHEN FILLED_NS_ITEMS.EM_ITEM_NUM IS NOT NULL THEN 'Y' ELSE 'N' END NS_FILLED_FLG
			,SUM(SLS_AMT) SLS_AMT
			,SUM(SLS_QTY) SLS_QTY
			,SUM(SLS_QTY*NCP.AMT) EXT_NCP
			,SUM(SLS_QTY*CP_COST.AMT) EXT_CP
			,SUM(DC_COST_AMT) EXT_WAC
			,SUM(LC.TOTAL_COST) LANDED_COST
			,SUM(DN3.AMT) DN3

INTO		#SLS
FROM		BTSMART.SALES.P_SALE_ITEM P --select top 10* from BTSMART.SALES.P_SALE_ITEM
		
JOIN		#ITEMS
ON			P.EM_ITEM_NUM = #ITEMS.EM_ITEM_NUM
AND			P.SLS_PROC_WRK_DT BETWEEN '2020-08-01' AND '2020-10-31'
--AND			DATEDIFF(MONTH,P.SLS_PROC_WRK_DT, GETDATE()) < 12
AND			P.GNRC_FLG = 'Y'
AND			P.SLS_CUST_CHN_ID NOT IN ('160','928','007','969','180','206','410','928')   --EXCLUDE MCK BUS UNITS
AND			P.SLS_CUST_BUS_TYP_CD NOT IN ('18','19','20') --EXCLUDE MCK BUS UNITS


LEFT JOIN	REFERENCE.DBO.V_IW_EM_ITEM I 
ON			P.EM_ITEM_NUM = I.EM_ITEM_NUM

LEFT JOIN	GEPRS_PRODUCT.EQV.V_EQV_ID_ITEMS EI
ON			P.EM_ITEM_NUM = EI.EM_ITEM_NUM
		
LEFT JOIN	GEPRS_DNC.DBO.T_ITEM_COST NCP
ON			P.EM_ITEM_NUM = NCP.EM_ITEM_NUM
AND			CAST(P.SO_PRC_DT AS DATE) BETWEEN NCP.EFF_DT AND NCP.END_DT
AND			NCP.COST_ID = '1855'

LEFT JOIN	GEPRS_DNC.dbo.T_ITEM_COST CP_COST
ON			P.EM_ITEM_NUM = CP_COST.EM_ITEM_NUM
AND			CP_COST.COST_ID = '66'
AND			CAST(GETDATE() AS DATE) BETWEEN CP_COST.EFF_DT AND CP_COST.END_DT

LEFT JOIN  GEPRS_DNC.dbo.T_ITEM_COST DN3			ON DN3.EM_ITEM_NUM = P.EM_ITEM_NUM 
													AND P.SLS_PROC_WRK_DT BETWEEN DN3.EFF_DT and DN3.END_DT 
													AND DN3.COST_ID = 34  -- 34= OS Dead Net 3	


LEFT JOIN OPS_SS_MCKSQL74.GX_RPT.dbo.T_NSTAR_COST LC
ON			P.EM_ITEM_NUM = LC.EM_ITEM_NUM
AND			P.SLS_PROC_WRK_DT BETWEEN LC.PRC_BEG_DT AND LC.PRC_END_DT
AND			I.SPLR_ACCT_NAM LIKE '%NORTHSTAR%'

JOIN		#CURR_CUSTS
ON			P.SLS_CUST_CHN_ID = #CURR_CUSTS.CHN_ID

LEFT JOIN	#PGM_TYPES
ON			P.YYPRC_PRGTYP_CD = #PGM_TYPES.PGM_TYP_CD

LEFT JOIN	#NS_ITEMS
ON			#NS_ITEMS.EM_ITEM_NUM = P.YYITM_ECON_ORIG_ITEM_NUM

--LEFT JOIN	#NS_ITEMS FILLED_NS_ITEMS
--ON			#NS_ITEMS.EM_ITEM_NUM = P.EM_ITEM_NUM	

GROUP BY	LEFT(CONVERT(varchar, P.SLS_PROC_WRK_DT,112),6)
			,P.SLS_CUST_CHN_ID
			,#CURR_CUSTS.CUSTOMER_NAME
			,#CURR_CUSTS.SEGMENT
			,I.GNRC_NAM
			,I.GNRC_ID
			,P.EM_ITEM_NUM
			,I.SELL_DSCR
			,EI.EQV_ID
			,I.SPLR_ACCT_NAM
			,CASE WHEN I.SPLR_ACCT_NAM LIKE '%NORTHSTAR%' THEN 'Y' ELSE 'N' END
			,#PGM_TYPES.PROGRAM
			,P.CNTRC_LEAD_TP_ID
			,CASE	WHEN P.ITEM_SUB_CD = 'Y' THEN 'OVERRIDE' 
				WHEN P.SUB_FLG = 'Y' THEN 'SUB'
				ELSE 'FILLED' END
			,CASE	WHEN P.ITEM_SUB_CD IN ('O','A') THEN 'OMIT'
				WHEN P.ITEM_SUB_CD IN ('B','P') THEN 'ALWAYS'
				ELSE ' '
				END
			,P.YYITM_ECON_ORIG_ITEM_NUM
			,CASE WHEN #NS_ITEMS.EM_ITEM_NUM IS NOT NULL THEN 'Y' ELSE 'N' END
			--,CASE WHEN FILLED_NS_ITEMS.EM_ITEM_NUM IS NOT NULL THEN 'Y' ELSE 'N' END;

--SELECT * FROM #SLS

----COST DATA
--IF OBJECT_ID('tempdb..#COST_DATA') IS NOT NULL DROP TABLE #COST_DATA;
--SELECT		#NS_ITEMS.EM_ITEM_NUM
--			,NCP_COST.AMT NCP_COST
--			,CP_COST.AMT CP_COST
--			,WAC_COST.COST_PRC_AMT WAC_COST

--INTO		#COST_DATA
--FROM		#NS_ITEMS

--LEFT JOIN	GEPRS_DNC.dbo.T_ITEM_COST NCP_COST
--ON			#NS_ITEMS.EM_ITEM_NUM = NCP_COST.EM_ITEM_NUM
--AND			NCP_COST.COST_ID = '1855'
--AND			CAST(GETDATE() AS DATE) BETWEEN NCP_COST.EFF_DT AND NCP_COST.END_DT

--LEFT JOIN	GEPRS_DNC.dbo.T_ITEM_COST CP_COST
--ON			#NS_ITEMS.EM_ITEM_NUM = CP_COST.EM_ITEM_NUM
--AND			CP_COST.COST_ID = '66'
--AND			CAST(GETDATE() AS DATE) BETWEEN CP_COST.EFF_DT AND CP_COST.END_DT

--LEFT JOIN	REFERENCE.dbo.V_IW_EM_ITEM WAC_COST
--ON			#NS_ITEMS.EM_ITEM_NUM = WAC_COST.EM_ITEM_NUM;

--SELECT * FROM #COST_DATA


--COMBINE THE DATA
IF OBJECT_ID('tempdb..#RESULTS') IS NOT NULL DROP TABLE #RESULTS;

SELECT		C.SLS_CUST_CHN_ID
			,C.CUSTOMER_NAME
			,C.SEGMENT
			,NI.EM_ITEM_NUM
			,NI.SELL_DSCR
			,NI.TOTAL_PKG_SIZE
			,NI.GCN
			,NI.GNRC_NAM
			,NI.EQV_ID
			,NI.INJECTABLE
			,S.PROGRAM
			,S.ORDR_TYPE
			,S.SUB_TYPE
			,S.ORIG_ORDR_ITEM
			,S.EM_ITEM_NUM FILLED_ITEM
			,S.NS_ORIG_ORDR
			,CASE WHEN S.NS_ORIG_ORDR = 'Y' OR (S.EM_ITEM_NUM = NI.EM_ITEM_NUM) THEN 'Y' ELSE 'N' END NS_FILLED_OR_ORDR
			,CAST(SUM(CASE WHEN NSTR_FLG = 'Y' THEN S.SLS_QTY ELSE 0 END)*4 AS DECIMAL(18,2)) NS_QTY
			,CAST(ISNULL(SUM(S.SLS_QTY),0)*4 AS DECIMAL(18,2)) TOT_QTY
			,CAST(SUM(CASE WHEN NSTR_FLG = 'Y' THEN S.SLS_AMT ELSE 0 END)*4 AS DECIMAL(18,2)) NS_SLS_AMT
			,CAST(ISNULL(SUM(S.SLS_AMT),0)*4 AS DECIMAL(18,2)) TOT_SLS_AMT
			,CAST(SUM(CASE WHEN NSTR_FLG = 'Y' THEN S.EXT_NCP ELSE 0 END)*4 AS DECIMAL(18,2)) NS_EXT_NCP
			,CAST(ISNULL(SUM(S.EXT_NCP),0)*4 AS DECIMAL(18,2)) TOT_EXT_NCP
			,CAST(SUM(CASE WHEN NSTR_FLG = 'Y' THEN S.EXT_WAC ELSE 0 END)*4 AS DECIMAL(18,2)) NS_EXT_WAC
			,CAST(ISNULL(SUM(S.EXT_WAC),0)*4 AS DECIMAL(18,2)) TOT_EXT_WAC
			,CAST(SUM(CASE WHEN NSTR_FLG = 'Y' THEN S.EXT_CP ELSE 0 END)*4 AS DECIMAL(18,2)) NS_EXT_CP
			,CAST(ISNULL(SUM(S.EXT_CP),0)*4 AS DECIMAL(18,2)) TOT_EXT_CP
			--,CAST(ISNULL(SUM(S.SLS_AMT),0) AS DECIMAL(18,2)) TOT_SLS_AMT
			--,CAST(ISNULL(SUM(S.SLS_QTY),0) AS DECIMAL(18,2)) TOT_QTY
			--,CAST(SUM(CASE WHEN S.NSTR_FLG = 'Y' THEN (S.LANDED_COST)
			--			WHEN S.PROGRAM = 'ONESTOP' THEN (S.DN3)
			--			WHEN S.PROGRAM = 'MULTISOURCE' THEN (S.EXT_CP)
			--			WHEN S.PROGRAM IS NULL THEN S.SLS_AMT * 0.98
			--			WHEN S.PROGRAM LIKE '%CONTRACT%' THEN (S.SLS_AMT) * 0.95
			--			ELSE 0
			--		END) AS DECIMAL(18,2)) TOT_COST


INTO		#RESULTS
FROM		(SELECT DISTINCT SLS_CUST_CHN_ID, CUSTOMER_NAME, SEGMENT FROM #SLS) C

CROSS JOIN	#NS_ITEMS NI

LEFT JOIN	#SLS S
ON			S.EQV_ID = NI.EQV_ID
AND			C.SLS_CUST_CHN_ID = S.SLS_CUST_CHN_ID



GROUP BY	C.SLS_CUST_CHN_ID
			,C.CUSTOMER_NAME
			,C.SEGMENT
			,NI.EM_ITEM_NUM
			,NI.SELL_DSCR
			,NI.TOTAL_PKG_SIZE
			,NI.GCN
			,NI.GNRC_NAM
			,NI.EQV_ID
			,NI.INJECTABLE
			,S.PROGRAM
			,S.ORDR_TYPE
			,S.SUB_TYPE
			,S.ORIG_ORDR_ITEM
			,S.EM_ITEM_NUM
			,S.NS_ORIG_ORDR
			,CASE WHEN S.NS_ORIG_ORDR = 'Y' OR (S.EM_ITEM_NUM = NI.EM_ITEM_NUM) THEN 'Y' ELSE 'N' END;


--UTILIZATION PULL
SELECT		*
			--CUSTOMER_NAME, EM_ITEM_NUM, SELL_DSCR, NS_QTY, TOT_QTY, NS_SLS_AMT, TOT_SLS_AMT, NS_EXT_NCP, TOT_EXT_NCP, NS_EXT_WAC, TOT_EXT_WAC
			--,CAST((CASE WHEN TOT_QTY <> 0 THEN (NS_QTY/TOT_QTY) ELSE 0 END) AS DECIMAL(18,4)) QTY_UTIL

FROM		#RESULTS


--WHERE		TOT_SLS_AMT <> 0
--WHERE		EM_ITEM_NUM NOT IN ('3644796','3758760','3758778','3758786','3773926')

ORDER BY	SLS_CUST_CHN_ID, EQV_ID, EM_ITEM_NUM;
--ORDER BY	CUSTOMER_NAME, EQV_ID, EM_ITEM_NUM;


--SELECT SUM(TOT_SLS_AMT) FROM #RESULTS WHERE SLS_CUST_CHN_ID <> '160'

--SELECT COUNT(DISTINCT EQV_ID) FROM #RESULTS

--SELECT DISTINCT 